### ISSUE TITLE
The deployment encountered an exception

### ISSUE THREAD

**Issue by Rodert** [bestinslot-xyz/OPI-LC#5]
i make `python3 brc20_light_client_sqlite.py` to get the following.

```bash
Trying to get events from http://5.78.108.233:8000
Event count:  182
Ticks refreshed in 0.29262495040893555 seconds
Traceback (most recent call last):
  File "brc20_light_client_sqlite.py", line 1303, in <module>
    if index_block(current_block):
  File "brc20_light_client_sqlite.py", line 751, in index_block
    transfer_inscribe(block_height, inscr_id, source_pkScript, source_wallet, tick, amount)
  File "brc20_light_client_sqlite.py", line 326, in transfer_inscribe
    execute_with_params('''insert into brc20_events (event_type, block_height, inscription_id, event)
  File "brc20_light_client_sqlite.py", line 51, in execute_with_params
    cur.execute(sql, obj)
sqlite3.OperationalError: near "returning": syntax error
rolling back
```

**Comment by samedcildir** [comment]
You should update your python. Some of the features that we've used are very new so they are not included in default SQLite library of older pythons.
